/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { ApplicationUser } from "./ApplicationUser";
import { ApplicationUserCountArgs } from "./ApplicationUserCountArgs";
import { ApplicationUserFindManyArgs } from "./ApplicationUserFindManyArgs";
import { ApplicationUserFindUniqueArgs } from "./ApplicationUserFindUniqueArgs";
import { CreateApplicationUserArgs } from "./CreateApplicationUserArgs";
import { UpdateApplicationUserArgs } from "./UpdateApplicationUserArgs";
import { DeleteApplicationUserArgs } from "./DeleteApplicationUserArgs";
import { ApplicationUserService } from "../applicationUser.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ApplicationUser)
export class ApplicationUserResolverBase {
  constructor(
    protected readonly service: ApplicationUserService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ApplicationUser",
    action: "read",
    possession: "any",
  })
  async _applicationUsersMeta(
    @graphql.Args() args: ApplicationUserCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ApplicationUser])
  @nestAccessControl.UseRoles({
    resource: "ApplicationUser",
    action: "read",
    possession: "any",
  })
  async applicationUsers(
    @graphql.Args() args: ApplicationUserFindManyArgs
  ): Promise<ApplicationUser[]> {
    return this.service.applicationUsers(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ApplicationUser, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ApplicationUser",
    action: "read",
    possession: "own",
  })
  async applicationUser(
    @graphql.Args() args: ApplicationUserFindUniqueArgs
  ): Promise<ApplicationUser | null> {
    const result = await this.service.applicationUser(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ApplicationUser)
  @nestAccessControl.UseRoles({
    resource: "ApplicationUser",
    action: "create",
    possession: "any",
  })
  async createApplicationUser(
    @graphql.Args() args: CreateApplicationUserArgs
  ): Promise<ApplicationUser> {
    return await this.service.createApplicationUser({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ApplicationUser)
  @nestAccessControl.UseRoles({
    resource: "ApplicationUser",
    action: "update",
    possession: "any",
  })
  async updateApplicationUser(
    @graphql.Args() args: UpdateApplicationUserArgs
  ): Promise<ApplicationUser | null> {
    try {
      return await this.service.updateApplicationUser({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ApplicationUser)
  @nestAccessControl.UseRoles({
    resource: "ApplicationUser",
    action: "delete",
    possession: "any",
  })
  async deleteApplicationUser(
    @graphql.Args() args: DeleteApplicationUserArgs
  ): Promise<ApplicationUser | null> {
    try {
      return await this.service.deleteApplicationUser(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
