/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { EventManagerService } from "../eventManager.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { EventManagerCreateInput } from "./EventManagerCreateInput";
import { EventManager } from "./EventManager";
import { EventManagerFindManyArgs } from "./EventManagerFindManyArgs";
import { EventManagerWhereUniqueInput } from "./EventManagerWhereUniqueInput";
import { EventManagerUpdateInput } from "./EventManagerUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class EventManagerControllerBase {
  constructor(
    protected readonly service: EventManagerService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: EventManager })
  @nestAccessControl.UseRoles({
    resource: "EventManager",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createEventManager(
    @common.Body() data: EventManagerCreateInput
  ): Promise<EventManager> {
    return await this.service.createEventManager({
      data: {
        ...data,

        city: data.city
          ? {
              connect: data.city,
            }
          : undefined,
      },
      select: {
        city: {
          select: {
            id: true,
          },
        },

        contactInfo: true,
        createdAt: true,
        id: true,
        isActive: true,
        name: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [EventManager] })
  @ApiNestedQuery(EventManagerFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "EventManager",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async eventManagers(@common.Req() request: Request): Promise<EventManager[]> {
    const args = plainToClass(EventManagerFindManyArgs, request.query);
    return this.service.eventManagers({
      ...args,
      select: {
        city: {
          select: {
            id: true,
          },
        },

        contactInfo: true,
        createdAt: true,
        id: true,
        isActive: true,
        name: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: EventManager })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EventManager",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async eventManager(
    @common.Param() params: EventManagerWhereUniqueInput
  ): Promise<EventManager | null> {
    const result = await this.service.eventManager({
      where: params,
      select: {
        city: {
          select: {
            id: true,
          },
        },

        contactInfo: true,
        createdAt: true,
        id: true,
        isActive: true,
        name: true,
        typeField: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: EventManager })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EventManager",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateEventManager(
    @common.Param() params: EventManagerWhereUniqueInput,
    @common.Body() data: EventManagerUpdateInput
  ): Promise<EventManager | null> {
    try {
      return await this.service.updateEventManager({
        where: params,
        data: {
          ...data,

          city: data.city
            ? {
                connect: data.city,
              }
            : undefined,
        },
        select: {
          city: {
            select: {
              id: true,
            },
          },

          contactInfo: true,
          createdAt: true,
          id: true,
          isActive: true,
          name: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: EventManager })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EventManager",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteEventManager(
    @common.Param() params: EventManagerWhereUniqueInput
  ): Promise<EventManager | null> {
    try {
      return await this.service.deleteEventManager({
        where: params,
        select: {
          city: {
            select: {
              id: true,
            },
          },

          contactInfo: true,
          createdAt: true,
          id: true,
          isActive: true,
          name: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
